import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import { Button, Space, DatePicker, Card } from "antd";
import { CiCircleFilled } from "@ant-design/icons";

const Home: NextPage = () => {
  const onChange = () => {};

  return (
    <div>
      <Head>
        <title>Juleølkalender</title>
        <meta name="juleølkalender" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Space direction="vertical">
        <Button type="primary">Primary Button</Button>
        <Button type="ghost">Ghost Button</Button>
        <DatePicker onChange={onChange} />
        <CiCircleFilled />
      </Space>
    </div>
  );
};

export default Home;
